# -*- coding: utf-8 -*-
"""형태소분석&불용어처리.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mCEbQGg3YTRKEm2fDCzhEZfM0Psw3PJ4

#형태소분석후 불용어 처리한 모델 입니다.
"""

from konlpy.tag import Okt
from gensim import corpora
from gensim.models import LdaModel, TfidfModel


# 형태소 분석기 초기화
okt = Okt()

# 텍스트 데이터를 리스트로 변환
documents = df['content'].tolist()

# 불용어 리스트 정의
stop_words = ["것", "수", "이", "그", "를", "를", "등", "과", "에", "가", '때', '의', '및']

# 각 문서를 형태소 분석 및 토큰화하고 불용어 제거
tokenized_documents = []

for document in documents:
    # 형태소 분석 수행 후 명사만 선택 (원하는 형태소 선택 가능)
    tokens = [word for word, pos in okt.pos(document) if pos in ['Noun'] and word not in stop_words]
    tokenized_documents.append(tokens)

# 사전 (Dictionary) 생성
dictionary = corpora.Dictionary(tokenized_documents)

# Tfidf 모델 생성
tfidf = TfidfModel(dictionary=dictionary)
corpus = [dictionary.doc2bow(tokens) for tokens in tokenized_documents]

# LDA 모델 생성
lda_model = LdaModel(corpus, num_topics=30, id2word=dictionary, passes=15)

# LDA 모델 출력
for idx, topic in lda_model.print_topics(-1):
    print(f"Topic #{idx}: {topic}")